# Generated by Django 5.0.2 on 2024-09-03 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('professor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('admin_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('admin_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'up_administrator',
            },
        ),
        migrations.CreateModel(
            name='Announcements',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('announcement_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=10000)),
            ],
            options={
                'db_table': 'up_announcements',
            },
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('course_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=255)),
                ('course_credit', models.IntegerField(default=3)),
                ('description', models.CharField(max_length=255)),
                ('course_faculty', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='professor.professor')),
            ],
            options={
                'db_table': 'up_courses',
            },
        ),
    ]
