# Generated by Django 5.0.2 on 2024-09-03 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('quiz_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('quiz_name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('total_marks', models.IntegerField(default=0)),
                ('course', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Admin.courses')),
            ],
            options={
                'db_table': 'up_quiz',
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('question_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=255, null=True)),
                ('question_type', models.CharField(choices=[('MCQ', 'mcq'), ('ONE_WORD', 'one word'), ('TRUE_OR_FALSE', 'true or false')], max_length=255, null=True)),
                ('answer', models.CharField(max_length=255, null=True)),
                ('options', models.CharField(max_length=255, null=True)),
                ('marks', models.IntegerField(null=True)),
                ('quiz_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz')),
            ],
            options={
                'db_table': 'uq_Questions',
            },
        ),
    ]
