# Generated by Django 5.0.2 on 2024-09-08 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='questions',
            table='up_Questions',
        ),
    ]
