# Generated by Django 5.0.2 on 2024-09-05 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
        ('resources', '0001_initial'),
        ('student', '0002_subjectselection'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmitedAssignment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('submited_assignment_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('assigned_marks', models.IntegerField(null=True)),
                ('assignment_solution', models.FileField(blank=True, db_column='assignment_file', null=True, upload_to='Files/assignmentsolutions')),
                ('assignment', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='resources.assignment')),
                ('course', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Admin.courses')),
                ('student', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
            options={
                'db_table': 'up_submitedassignment',
            },
        ),
    ]
