# Generated by Django 5.0.2 on 2024-09-06 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
        ('student', '0003_submitedassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizScore',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('quizscore_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('marks_scored', models.IntegerField(null=True)),
                ('quiz', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz')),
                ('student', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
            options={
                'db_table': 'up_quiz_score',
            },
        ),
    ]
